import fs from 'fs';
import path from 'path';
import { LanguageAgentResult } from './language-agent';
import { SuiteJudgement } from './qa-judge-agent';
import { JudgeResult } from '../utils/claude-client';

export interface BugReport {
  id: string;
  lang: string;
  severity: 'critical' | 'major' | 'minor';
  title: string;
  description: string;
  checks: string[];
  screenshotPath?: string;
  githubIssue: GitHubIssuePayload;
}

export interface GitHubIssuePayload {
  title: string;
  body: string;
  labels: string[];
}

const REPORTS_DIR = path.resolve(__dirname, '../reports/bugs');

function ensureReportsDir(): void {
  fs.mkdirSync(REPORTS_DIR, { recursive: true });
}

function scorToSeverity(score: number): 'critical' | 'major' | 'minor' {
  if (score < 0.4) return 'critical';
  if (score < 0.7) return 'major';
  return 'minor';
}

function buildGitHubBody(report: Omit<BugReport, 'githubIssue'>): string {
  const lines: string[] = [
    `## Bug Report — Language: ${report.lang.toUpperCase()}`,
    '',
    `**Severity:** ${report.severity}`,
    `**Test run ID:** ${report.id}`,
    '',
    '### Description',
    report.description,
    '',
    '### Failed Checks',
    ...report.checks.map(c => `- ${c}`),
    '',
    '### Steps to Reproduce',
    '1. Open app in browser (iPad viewport 1024×1366)',
    `2. Select language: ${report.lang}`,
    '3. Inject test profile via localStorage key `app-profiles`',
    '4. Run automated language agent checks',
    '',
    '### Environment',
    '- Device: iPad Pro (simulated, Playwright)',
    '- Viewport: 1024×1366, touch enabled',
    '- App: Idris Learning PWA',
    '',
    report.screenshotPath
      ? `### Screenshot\n![screenshot](${path.basename(report.screenshotPath)})\n`
      : '',
    '---',
    '_Auto-generated by BugReportAgent · idris-learning-app QA_',
  ];
  return lines.join('\n');
}

export class BugReportAgent {
  /**
   * Generate bug reports for all languages that did not pass the judge threshold.
   */
  generateReports(
    results: LanguageAgentResult[],
    judgements: Record<string, JudgeResult>,
  ): BugReport[] {
    ensureReportsDir();
    const bugs: BugReport[] = [];

    for (const result of results) {
      const judgement = judgements[result.lang];
      if (!judgement || judgement.verdict === 'pass') continue;

      const failedChecks = result.checks
        .filter(c => !c.passed)
        .map(c => `${c.name}: ${c.detail || 'no detail'}`);

      if (failedChecks.length === 0 && result.errors.length === 0) continue;

      const severity = scorToSeverity(judgement.score);
      const id = `BUG-${result.lang.toUpperCase()}-${Date.now()}`;
      const title = `[${result.lang.toUpperCase()}] ${judgement.reason}`;
      const description = [
        judgement.reason,
        ...(judgement.issues.length > 0 ? ['', 'Issues:', ...judgement.issues.map(i => `- ${i}`)] : []),
        ...(result.errors.length > 0 ? ['', 'Agent errors:', ...result.errors.map(e => `- ${e}`)] : []),
      ].join('\n');

      const report: Omit<BugReport, 'githubIssue'> = {
        id,
        lang: result.lang,
        severity,
        title,
        description,
        checks: failedChecks,
        screenshotPath: result.screenshotPath,
      };

      const labels = [
        'bug',
        `lang:${result.lang}`,
        `severity:${severity}`,
        'auto-qa',
      ];

      const githubIssue: GitHubIssuePayload = {
        title,
        body: buildGitHubBody(report),
        labels,
      };

      const fullReport: BugReport = { ...report, githubIssue };
      bugs.push(fullReport);

      // Write Markdown report
      const mdPath = path.join(REPORTS_DIR, `${id}.md`);
      fs.writeFileSync(mdPath, githubIssue.body, 'utf8');

      // Write GitHub Issue JSON (for use with gh CLI or API)
      const jsonPath = path.join(REPORTS_DIR, `${id}.github.json`);
      fs.writeFileSync(jsonPath, JSON.stringify(githubIssue, null, 2), 'utf8');
    }

    return bugs;
  }

  /**
   * Write a suite summary report to reports/bugs/SUMMARY.md.
   */
  writeSummary(suite: SuiteJudgement, bugs: BugReport[]): string {
    ensureReportsDir();
    const lines = [
      '# QA Suite Summary',
      '',
      `**Overall Score:** ${suite.overallScore.toFixed(2)}`,
      `**Verdict:** ${suite.overallVerdict.toUpperCase()}`,
      `**Date:** ${new Date().toISOString()}`,
      '',
      '## Per-Language Results',
      '',
      '| Language | Score | Verdict | Notes |',
      '|----------|-------|---------|-------|',
      ...Object.entries(suite.perLanguage).map(([lang, j]) =>
        `| ${lang.toUpperCase()} | ${j.score.toFixed(2)} | ${j.verdict} | ${j.reason} |`
      ),
      '',
    ];

    if (suite.criticalIssues.length > 0) {
      lines.push('## Critical Issues', '');
      suite.criticalIssues.forEach(i => lines.push(`- ${i}`));
      lines.push('');
    }

    if (bugs.length > 0) {
      lines.push('## Bug Reports Generated', '');
      bugs.forEach(b => lines.push(`- [${b.severity.toUpperCase()}] ${b.title}`));
      lines.push('');
    }

    lines.push('---', '_Generated by BugReportAgent · idris-learning-app QA_');

    const summaryPath = path.join(REPORTS_DIR, 'SUMMARY.md');
    fs.writeFileSync(summaryPath, lines.join('\n'), 'utf8');
    return summaryPath;
  }
}
