/**
 * BugReporter — generates Markdown bug reports and GitHub Issues JSON.
 *
 * Outputs:
 *   reports/bugs/YYYY-MM-DD-<id>.md
 *   reports/bugs/YYYY-MM-DD-<id>.github.json
 *   reports/bugs/SUMMARY.md
 */

import fs from 'fs';
import path from 'path';
import { AgentResult } from '../agents/base-agent';
import { LanguageScore, SuiteScore } from '../judge/qa-judge';

const REPORTS_DIR = path.resolve(__dirname, '../reports/bugs');
const DATE_PREFIX = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

export interface BugReport {
  id: string;
  lang: string;
  severity: 'critical' | 'major' | 'minor';
  title: string;
  body: string;
  failedChecks: string[];
  screenshotPath?: string;
  githubIssue: GitHubIssuePayload;
}

export interface GitHubIssuePayload {
  title: string;
  body: string;
  labels: string[];
}

function ensureDir(): void {
  fs.mkdirSync(REPORTS_DIR, { recursive: true });
}

function toSeverity(score: number): 'critical' | 'major' | 'minor' {
  if (score < SCORE_FAIL) return 'critical';
  if (score < SCORE_PASS) return 'major';
  return 'minor';
}

const SCORE_FAIL = 0.4;
const SCORE_PASS = 0.7;

function buildMarkdownBody(
  report: Omit<BugReport, 'githubIssue'>,
  score: LanguageScore,
): string {
  const lines = [
    `## Bug Report — [${report.lang.toUpperCase()}] ${score.reason}`,
    '',
    `**ID:** \`${report.id}\``,
    `**Severity:** ${report.severity}`,
    `**QA Score:** ${score.score.toFixed(2)} (${score.verdict})`,
    `**Date:** ${new Date().toISOString()}`,
    '',
    '### Failed Checks',
    ...(report.failedChecks.length > 0
      ? report.failedChecks.map(c => `- ${c}`)
      : ['- (none — score below threshold despite all checks passing)']),
    '',
    ...(score.issues.length > 0 ? ['### Judge Issues', ...score.issues.map(i => `- ${i}`), ''] : []),
    '### Steps to Reproduce',
    '1. Open app in browser (iPad viewport 1024×1366, touch enabled)',
    `2. Select language: **${report.lang}**`,
    '3. Inject test profile via localStorage key `app-profiles`',
    '4. Run: `npx playwright test agents/' + report.lang + '-agent.spec.ts`',
    '',
    '### Environment',
    '- Device: iPad Pro (Playwright simulation)',
    '- Viewport: 1024×1366, touch mode',
    '- App: Idris Learning PWA',
    '',
    report.screenshotPath
      ? `### Screenshot\n![screenshot](../../${path.relative(REPORTS_DIR, report.screenshotPath).replace(/\\/g, '/')})\n`
      : '',
    '---',
    '_Auto-generated by BugReporter · idris-learning-app QA_',
  ];
  return lines.join('\n');
}

/** Generate bug reports for all languages that warn or fail. */
export function generateReports(
  results: AgentResult[],
  scores: Record<string, LanguageScore>,
): BugReport[] {
  ensureDir();
  const bugs: BugReport[] = [];

  for (const result of results) {
    const score = scores[result.lang];
    if (!score || score.verdict === 'pass') continue;

    const failedChecks = result.checks
      .filter(c => !c.passed)
      .map(c => `${c.name}: ${c.detail ?? 'no detail'}`);

    // Skip if everything passed but score is oddly low (judge override)
    if (failedChecks.length === 0 && result.errors.length === 0 && score.verdict !== 'fail') continue;

    const severity = toSeverity(score.score);
    const id = `${DATE_PREFIX}-BUG-${result.lang.toUpperCase()}-${Date.now()}`;
    const title = `[${result.lang.toUpperCase()}] ${score.reason}`;

    const reportBase: Omit<BugReport, 'githubIssue'> = {
      id,
      lang: result.lang,
      severity,
      title,
      body: '',
      failedChecks,
      screenshotPath: result.screenshotPath,
    };

    const body = buildMarkdownBody(reportBase, score);
    reportBase.body = body;

    const githubIssue: GitHubIssuePayload = {
      title,
      body,
      labels: ['bug', `lang:${result.lang}`, `severity:${severity}`, 'auto-qa'],
    };

    const full: BugReport = { ...reportBase, githubIssue };
    bugs.push(full);

    // Write Markdown
    fs.writeFileSync(path.join(REPORTS_DIR, `${id}.md`), body, 'utf8');

    // Write GitHub Issues JSON (ready for `gh issue create --body-file`)
    fs.writeFileSync(
      path.join(REPORTS_DIR, `${id}.github.json`),
      JSON.stringify(githubIssue, null, 2),
      'utf8',
    );
  }

  return bugs;
}

/** Write SUMMARY.md with suite-level results table. */
export function writeSummary(suite: SuiteScore, bugs: BugReport[]): string {
  ensureDir();
  const lines = [
    '# QA Suite Summary',
    '',
    `**Date:** ${new Date().toISOString()}`,
    `**Overall Score:** ${suite.overallScore.toFixed(2)}`,
    `**Verdict:** ${suite.overallVerdict.toUpperCase()}`,
    '',
    '## Per-Language Scores',
    '',
    '| Language | Score | Verdict | Notes |',
    '|----------|-------|---------|-------|',
    ...Object.entries(suite.perLanguage).map(
      ([lang, s]) => `| ${lang.toUpperCase()} | ${s.score.toFixed(2)} | ${s.verdict} | ${s.reason} |`,
    ),
    '',
  ];

  if (suite.criticalIssues.length > 0) {
    lines.push('## Critical Issues', '');
    suite.criticalIssues.forEach(i => lines.push(`- ${i}`));
    lines.push('');
  }

  if (bugs.length > 0) {
    lines.push('## Bug Reports', '');
    bugs.forEach(b => lines.push(`- **[${b.severity.toUpperCase()}]** \`${b.id}\` — ${b.title}`));
    lines.push('');
  }

  lines.push('---', '_Generated by BugReporter · idris-learning-app QA_');

  const summaryPath = path.join(REPORTS_DIR, 'SUMMARY.md');
  fs.writeFileSync(summaryPath, lines.join('\n'), 'utf8');
  return summaryPath;
}
